
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tedro
 */
public class gamePlay extends javax.swing.JFrame{

    /**
     * Creates new form gamePlay
     */
    public gamePlay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(40, 40, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(649, 240));

        jLabel1.setBackground(new java.awt.Color(20, 20, 20));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("SCORE:");

        jLabel2.setBackground(new java.awt.Color(20, 20, 20));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Player X:");

        jLabel3.setBackground(new java.awt.Color(20, 20, 20));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Player O:");

        jLabel4.setBackground(new java.awt.Color(20, 20, 20));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setBackground(new java.awt.Color(20, 20, 20));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton10.setBackground(new java.awt.Color(20, 20, 20));
        jButton10.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jButton10.setForeground(new java.awt.Color(240, 240, 0));
        jButton10.setText("Restart!");
        jButton10.setFocusable(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(40, 40, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton1.setForeground(new java.awt.Color(220, 220, 0));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jButton2.setBackground(new java.awt.Color(40, 40, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton2.setForeground(new java.awt.Color(220, 220, 0));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jButton3.setBackground(new java.awt.Color(40, 40, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton3.setForeground(new java.awt.Color(220, 220, 0));
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jButton4.setBackground(new java.awt.Color(40, 40, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton4.setForeground(new java.awt.Color(220, 220, 0));
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel14);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jButton5.setBackground(new java.awt.Color(40, 40, 0));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton5.setForeground(new java.awt.Color(220, 220, 0));
        jButton5.setFocusable(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel15);

        jPanel16.setLayout(new java.awt.BorderLayout());

        jButton6.setBackground(new java.awt.Color(40, 40, 0));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton6.setForeground(new java.awt.Color(220, 220, 0));
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel16);

        jPanel17.setLayout(new java.awt.BorderLayout());

        jButton7.setBackground(new java.awt.Color(40, 40, 0));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton7.setForeground(new java.awt.Color(220, 220, 0));
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel17);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jButton8.setBackground(new java.awt.Color(40, 40, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton8.setForeground(new java.awt.Color(220, 220, 0));
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel18);

        jPanel19.setLayout(new java.awt.BorderLayout());

        jButton9.setBackground(new java.awt.Color(40, 40, 0));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        jButton9.setForeground(new java.awt.Color(220, 220, 0));
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel19);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int countX = 0;
    private int countO = 0;
    private int scoreX = 0;
    private int scoreO = 0;
    private Boolean play = true;
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(play){ 
        if((countX < countO || countX == countO) && "".equals(jButton1.getText())){
            jButton1.setText("X");
            countX += 1;
            
        }
        else if(countO < countX && "".equals(jButton1.getText())){
            jButton1.setText("O");
            countO += 1;
            
        }
        gameRule();
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(play){
        if((countX < countO || countX == countO) && "".equals(jButton2.getText())){
            jButton2.setText("X");
            countX += 1;
        }
        else if(countO < countX && "".equals(jButton2.getText())){
            jButton2.setText("O");
            countO += 1;
        }
        gameRule();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(play){
        if((countX < countO || countX == countO) && "".equals(jButton3.getText())){
            jButton3.setText("X");
            countX += 1;
        }
        else if(countO < countX && "".equals(jButton3.getText())){
            jButton3.setText("O");
            countO += 1;
        }
        gameRule();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(play){
            if((countX < countO || countX == countO) && "".equals(jButton4.getText())){
            jButton4.setText("X");
            countX += 1;
        }
        else if(countO < countX && "".equals(jButton4.getText())){
            jButton4.setText("O");
            countO += 1;
        }
        gameRule();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(play){
            if((countX < countO || countX == countO) && "".equals(jButton5.getText())){
            jButton5.setText("X");
            countX += 1;
        }
        else if(countO < countX && "".equals(jButton5.getText())){
            jButton5.setText("O");
            countO += 1;
        }
        gameRule();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(play){
            if((countX < countO || countX == countO) && "".equals(jButton6.getText())){
            jButton6.setText("X");
            countX += 1;
        }
        else if(countO < countX && "".equals(jButton6.getText())){
            jButton6.setText("O");
            countO += 1;
        }
        gameRule();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(play){
            if((countX < countO || countX == countO) && "".equals(jButton7.getText())){
            jButton7.setText("X");
            countX += 1;
        }
        else if(countO < countX && "".equals(jButton7.getText())){
            jButton7.setText("O");
            countO += 1;
        }
        gameRule();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(play){if((countX < countO || countX == countO) && "".equals(jButton8.getText())){
            jButton8.setText("X");
            countX += 1;
        }
        else if(countO < countX && "".equals(jButton8.getText())){
            jButton8.setText("O");
            countO += 1;
        }
        gameRule();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(play){
            if((countX < countO || countX == countO) && "".equals(jButton9.getText())){
            jButton9.setText("X");
            countX += 1;
        }
        else if(countO < countX && "".equals(jButton9.getText())){
            jButton9.setText("O");
            countO += 1;
        }
        gameRule();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         play = true;
            jButton1.setText("");
            jButton2.setText("");
            jButton3.setText("");
            jButton4.setText("");
            jButton5.setText("");
            jButton6.setText("");
            jButton7.setText("");
            jButton8.setText("");
            jButton9.setText("");
            countX = 0;
            countO = 0;
            jButton10.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    public void gameRule(){
        if((jButton1.getText().equals(jButton2.getText())&&jButton1.getText().equals(jButton3.getText())&&(!"".equals(jButton1.getText())))|| 
                (jButton1.getText().equals(jButton4.getText())&&jButton1.getText().equals(jButton7.getText())&&(!"".equals(jButton1.getText())))||
                (jButton7.getText().equals(jButton8.getText())&&jButton7.getText().equals(jButton9.getText())&&(!"".equals(jButton7.getText())))||
                (jButton3.getText().equals(jButton6.getText())&&jButton3.getText().equals(jButton9.getText())&&(!"".equals(jButton3.getText())))||
                (jButton1.getText().equals(jButton5.getText())&&jButton1.getText().equals(jButton9.getText())&&(!"".equals(jButton1.getText())))||
                (jButton3.getText().equals(jButton5.getText())&&jButton3.getText().equals(jButton9.getText())&&(!"".equals(jButton3.getText())))||
                (jButton2.getText().equals(jButton5.getText())&&jButton2.getText().equals(jButton8.getText())&&(!"".equals(jButton2.getText())))||
                (jButton4.getText().equals(jButton5.getText())&&jButton4.getText().equals(jButton6.getText()))&&(!"".equals(jButton4.getText()))){
            play = false;
            if (countX > countO){
                scoreX += 1;
            }
            else if(countX == countO){
                scoreO += 1; 
            }
            jLabel4.setText(String.valueOf(new Integer(scoreX)));
            jLabel5.setText(String.valueOf(new Integer(scoreO)));
            jButton10.setVisible(true);
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gamePlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gamePlay().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    
}
